#Database
POSTGRES_SQL_USERNAME: mckenzie
POSTGRES_SQL_PASSWORD: mckenzie1234
POSTGRES_SQL_HOST: 127.0.0.1
POSTGRES_SQL_PORT: 5432
POSTGRES_SQL_DB: EmailServices

SERVER_PORT: 3000
ACTIVE_PROFILE: prod

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: pandit.alabi@devlaps.co
EMAIL_PASSWORD: rbsv gzxo ktzk xntq
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}
