#Database
POSTGRES_SQL_USERNAME: postgres
POSTGRES_SQL_PASSWORD: postgres
POSTGRES_SQL_HOST: http://localhost

SERVER_PORT: 3000

#Email Config
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: panditmckenzie@gmail.com
EMAIL_PASSWORD: nels uqof qhfj rhgp
VERIFY_EMAIL_HOST: http://localhost:${SERVER_PORT}